apiVersion: v1
kind: ConfigMap
metadata:
   name: nginx-configmap3
   namespace: default
data:
  index.html: |
    <html>
    <h1>BlueTeam, Welcome to Kubernetes</h1>
    </br>
    <h1><p>This is Deployment One</p></h1>
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: nginx-configmap4
   namespace: default
data:
  myindex.html: |
    <html>
    <h1>BlueTeam, Welcome Back to Kubernetes</h1>
    </br>
    <h1><p>This is Deployment Two</p></h1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
    namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-index-file
      volumes:
        - name: nginx-index-file
          configMap:
            name: nginx-configmap3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxalpine
  labels:
    name: nginxalpine
    namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginxalpine
    template:
      metadata:
        labels:
          name: nginxalpine
      spec:
        containers:
        - name:: nginxalpine
          image: nginx:1.23.3-alpine-perl
          ports:
          - containerPort: 80
         volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-index-file
      volumes:
        - name: nginx-index-file
          configMap:
            name: nginx-configmap4
---
apiVersion: v1
kind: Service
metadata:
  name: podnode
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    nodePort: 30080
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-current-date
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 30
      template:
        spec:
          containers:
          - name: print-current-date
            image: nginx:1.22.1-alpine
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - date; echo Hello, this is a CronJob test
          restartPolicy: OnFailure
      parallelism: 1
      completions: 1
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 3