apiVersion: v1
kind: Pod
metadata:
  name: shared-storage 
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: debian-container
      image: debian
      volumeMounts:
        - name: shared-data
          mountPath: /data
      command: ["/bin/sh"]
      args: ["-c", "echo Level Up Blue Team! > /data/index.html"]
---
apiVersion: v1
kind: Service
metadata:
  name: podnode
spec:
  type: NodePort
  selector:
    app: nginx-container
  ports:
  - port: 80
    nodePort: 30010