apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox:stable
      command: ['sh', '-c', 'echo Hello, world! > /voldata/hello.txt; sleep 3600']
      volumeMounts: 
      - name: voldata
        mountPath: /voldata
  volumes: 
  - name: voldata
    emptyDir: {}