apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
       labels:
          app: web-deployment
    spec:
      containers: 
      - name: nginx
        image: nginx:stable